services:
  db:
    image: postgres:16
    container_name: ecommerce_postgres_db # Konteyner adı
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456seven" # !!! GÜVENLİK UYARISI: Bu şifre GÜVENLİ DEĞİLDİR !!!
      POSTGRES_USER: "ecommerce_user"  # Veritabanı kullanıcı adı
      POSTGRES_DB: "ecommerce_db"      # Veritabanı adı
    ports:
      - "5432:5432" # Host portu 5432 meşgulse bunu değiştirin (örn: "5433:5432")
    volumes:
      - postgres_data:/var/lib/postgresql/data # Veri saklama alanı

volumes:
  postgres_data:    # Veri saklama alanının tanımı